name = "BioVossEncoder"
uuid = "e7894126-fa72-4101-935a-4d6cb73e7565"
authors = ["Camilo García-Botero<ca.garcia2@uniandes.edu.co>"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
BioSequences = "3"
PrecompileTools = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]