name = "BioBinarySeq"
uuid = "e7894126-fa72-4101-935a-4d6cb73e7565"
authors = ["Camilo García<ca.garcia2@uniandes.edu.co>"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"

[compat]
BioSequences = "3"
julia = "1.9"
